### ISSUE TITLE
Can't install on MacOS x86

### ISSUE THREAD

**Issue by Joebeazelman** [reznikmm/als-alire-index#10]
I tried to install it via Alire based on the instructions in the repo, but it posted the following warning:

```
arn: Could not find a complete solution for ada_language_server=23.0.17
Build will fail unless externals are made available, do you want to continue?
[Y] Yes  [N] No  (default is No) Y
warn: Generating possibly incomplete environment because of missing dependencies
ⓘ Running post_fetch actions for xmlada=23.0.0...
```

It repeatedly asked if I wanted to continue and I answered Yes. Eventually, I answered "No" and it failed with the following error:

```
ⓘ Running post_fetch actions for templates_parser=23.0.0...
ⓘ Running post_fetch actions for libgpr2=24.0.0-20230509...
fatal: destination path 'gprconfig_kb' already exists and is not an empty directory.
error: A post-fetch action failed, re-run with -vv -d for details
```

What do I do?

**Comment by reznikmm** [comment]
Hello. I guess `alr` can't find the solution because `libgmp` is missing on MacOS. I guess, you need to fetch `libgmp` somewhere and set `LIBRARY_PATH` environment to point it.
I suggest you find and delete `gprconfig_kb` directory (`ada_language_server_23.0.17_62ec5657/alire/cache/dependencies/libgpr2_24.0.0_ff927a8e/gprconfig_kb`), then try again. Or clean up everything. My `libgpr2.toml` script clones this directory in the post-fetch action and can't do it twice.
I doubt the last ALS could be built with GNAT CE 2021 now. I don't have Mac OS to try, unfortunately.
PS Don't hesitate to send a patch to README.md if you have ideas how to improve build instructions.
